AOJ/AOJ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('problem/', include('problem.urls')),
    path('contest/', include('contest.urls')),
    path('competitve/', include('competitive.urls')),
    path('clarification/', include('clarification.urls')),
    path('jury/', include('jury.urls')),
    path('public/', include('public.urls')),
    path('control/', include('control.urls')),
    path('site/', include('site_admin.urls')),
    path('judgeserver/', include('judgeserver.urls')),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AOJ/competitive/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('submit/', views.submit, name='submit'),
    path('problem/', views.active_contest_problem, name='active_contest_problem'),
    path('submit/language/', views.ajax_get_language_list, name='ajax_get_language_list'),
    path('scoreboard/public/', views.public_scoreboard, name='public_scoreboard'),
    path('scoreboard/public/refresh/', views.public_scoreboard_refresh, name='public_scoreboard_refresh'),
    path('scoreboard/jury/', views.jury_scoreboard, name='jury_scoreboard'),
    path('scoreboard/jury/refresh/', views.jury_scoreboard_refresh, name='jury_scoreboard_refresh'),
    path('submissions/contest-select/', views.view_submit_contest_select, name='view_submit_contest_select'),
    path('submissions/<int:contest_id>/', views.view_submissions, name='view_submission'),
    path('submit-detail/<int:submit_id>/', views.submission_detail, name='submission_detail'),
    path('rejudge/filter/', views.rejudge_submission_filter, name='rejudge_submission_filter'),
    path('submission/filter/', views.view_submission_filter, name='view_submission_filter'),
    path('specific-problem-submit/', views.specific_problem_submission, name='specific_problem_submission'),
    path('single-rejudge/<int:submit_id>/', views.single_rejudge, name='single_rejudge'),
    path('multi-rejudge/<int:problem_id>/<int:contest_id>/<int:user_id>/', views.multi_rejudge, name='multi_rejudge'),
    path('rejudge/contest-select/', views.rejudge_contest_select, name='rejudge_contest_select'),
    path('rejudge/submission-list/<int:contest_id>/', views.rejudge_submission_list, name='rejudge_submission_list'),
    path('rejudge/process/', views.ajax_rejudge, name='ajax_rejudge'),
    path('view-result/<int:contest_id>/', views.deactivate_contest_scoreboard, name='deactivate_contest_scoreboard'),
    path('submit-editor/', views.public_submit_editor, name='public_submit_editor'),
]

AOJ/problem/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('list/', views.problem_list, name='problem_list'),
    path('add/', views.addProblem, name='add_problem'),
    path('add-zip/', views.addProblemZIP, name='add_problem_zip'),
    path('edit/<int:problem_id>/', views.edit_problem, name='edit_problem'),
    path('delete/<int:problem_id>/', views.delete_problem, name='delete_problem'),
    path('delete-done/<int:problem_id>/', views.delete_problem_done, name='delete_problem_done'),
    path('testcase/<int:problem_id>/', views.testcase, name='testcase'),
    path('delete-testcase/<int:testcase_id>/', views.delete_testcase, name='delete_testcase'),
    path('delete-testcase-done/<int:testcase_id>/', views.delete_testcase_done, name='delete_testcase_done'),

]

AOJ/competitive/models.py
from django.db import models
from problem.models import TestCase, Problem
from contest.models import Contest
from authentication.models import User
from time import time
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.utils import timezone
# Create your models here.

result_lists=(('Correct', 'Correct'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Wrong Answer', 'Wrong Answer'), 
    ('Compiler Error', 'Compiler Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'),
    ('Run Time Error', 'Run Time Error'), ('No Output', 'No Output')
)

def testcase_output_directory_upload(instance, filename):
    problem_title = instance.submit.problem.title.replace(' ', '')
    testcase_title = instance.test_case.name.replace(' ', '')
    # filename = filename.replace(' ','')
    return 'file/user_{0}/{1}/{2}/output_{3}.out'.format(instance.submit.user.id, problem_title, instance.submit.id, testcase_title)


def submit_file_directory_upload(instance, filename):
    problem_title = instance.problem.title.replace(' ', '')
    filename = filename.replace(' ','')
    return 'file/user_{0}/{1}/{2}/{3}'.format(instance.user.id, problem_title, instance.id, filename)
    # return 'file/user_{0}/{1}/{2}/{3}'.format(instance.user.id, problem_title, time() , filename)


class Language(models.Model):
    name = models.CharField(max_length=200, unique=True)
    compile_command = models.CharField(max_length=300, help_text="use @ to represent file_name with extension and # with out extension")
    run_command = models.CharField(max_length=300, help_text='use @ to represent file_name with extension and # with out extension')
    extension = models.CharField(max_length=200, blank=True)
    editor_mode = models.CharField(max_length=200, blank=True)
    # enable = 

    def __str__(self):
        return self.name


class Submit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    result = models.CharField(max_length=200, choices=result_lists)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    submit_file = models.FileField(upload_to=submit_file_directory_upload)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE, null=True, blank=True)
    submit_time = models.DateTimeField()

    def __str__(self):
        return self.problem.title + ' by ' + self.user.username + ' for _sid '+str(self.pk)
   

class TestcaseOutput(models.Model):
    output_file = models.FileField(upload_to=testcase_output_directory_upload)
    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    submit = models.ForeignKey(Submit, on_delete=models.CASCADE)
    result = models.CharField(max_length=200, choices=result_lists)                                       
    execution_time = models.DecimalField(decimal_places=8, max_digits=12, default=0.00, validators=[MinValueValidator(Decimal('0.00'))])
    memory_usage = models.DecimalField(decimal_places=8, max_digits=12, default=0.00, validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        unique_together = ('test_case', 'output_file')

    def __str__(self):
        return self.submit.__str__() + ' test case ' + self.test_case.name 
    
        
class RankcacheJury(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE, limit_choices_to={'enable': True})
    user = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'role__short_name': "contestant"})
    point = models.DecimalField(default=0.0, decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.00'))])
    punish_time = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('contest', 'user')

    def __str__(self):
        return self.user.username + " on " + self.contest.title
 

class RankcachePublic(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE, limit_choices_to={'enable': True})
    user = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'role__short_name': "contestant"})
    point = models.DecimalField(default=0.0, decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.00'))])
    punish_time = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('contest', 'user')

    def __str__(self):
        return self.user.username + " on " + self.contest.title
 

class ScorecacheJury(models.Model):
    rank_cache = models.ForeignKey(RankcacheJury, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    submission = models.PositiveSmallIntegerField(default=0)
    punish = models.PositiveSmallIntegerField(default=0)
    # pending = models.PositiveSmallIntegerField(default=0)
    correct_submit_time = models.DateTimeField(null=True, blank=True)
    is_correct = models.BooleanField(default=False)
    judging = models.PositiveSmallIntegerField(default=0)
    class Meta:
        unique_together = ('rank_cache', 'problem')

    def __str__(self):
        return self.rank_cache.user.username + " on " + self.rank_cache.contest.title + ' for problem ' + self.problem.title


class ScorecachePublic(models.Model):
    rank_cache = models.ForeignKey(RankcachePublic, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    submission = models.PositiveSmallIntegerField(default=0)
    punish = models.PositiveSmallIntegerField(default=0)
    pending = models.PositiveSmallIntegerField(default=0)
    correct_submit_time = models.DateTimeField(null=True, blank=True)
    is_correct = models.BooleanField(default=False)
    judging = models.PositiveSmallIntegerField(default=0)
    class Meta:
        unique_together = ('rank_cache', 'problem')

    def __str__(self):
        return self.rank_cache.user.username + " on " + self.rank_cache.contest.title + ' for problem ' + self.problem.title

AOJ/problem/models.py
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal
from time import time
from authentication.validators import validate_problem_file_extension,\
    validate_testcase_in_file_extension, validate_testcase_out_file_extension

def problem_directory_upload(instance, filename):
    problem_title = instance.title.replace(' ', '')
    filename = filename.replace(' ','')
    return 'file/problem_{0}_{1}/{2}'.format(problem_title, instance.id, filename)
    # return 'file/problem_{0}/{1}/{2}'.format(problem_title, time() , filename)


def testcase_directory_upload(instance, filename):
    problem_title = instance.problem.title.replace(' ', '')
    filename = filename.replace(' ','')
    return 'file/problem_{0}_{1}/testcase/{2}'.format(problem_title, instance.problem.id, filename)
    # return 'file/testcase_{0}/{1}'.format(problem_title+"_"+str(instance.problem.id), filename)


# Create your models here.

class Problem(models.Model):
    title = models.CharField(max_length=200, unique=True, help_text="Enter problem title")
    short_name = models.CharField(max_length=10)
    pdf = models.FileField(upload_to=problem_directory_upload, unique=True, validators=[validate_problem_file_extension])
    point = models.DecimalField(default=1.0, decimal_places=2, max_digits=10,
                                validators=[MinValueValidator(Decimal('0.01'))])
    time_limit = models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.01'))],
                                     help_text='enter time limit in second')
    memory_limit = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=10,
                                       validators=[MinValueValidator(Decimal('0.01'))],
                                       help_text='Enter memory limit in mega bytes')
    ballon = models.CharField(max_length=10, default="#ffffff")
    error = models.DecimalField(default=0.0, decimal_places=20, max_digits=22,
                                       validators=[MinValueValidator(Decimal('0.00'))],
                                       help_text='maximum absolute or relative error')
    is_public =models.BooleanField(default=False)

    def __str__(self):
        return self.title


class TestCase(models.Model):
    name = models.CharField(max_length=200)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    input = models.FileField(upload_to=testcase_directory_upload, validators=[validate_testcase_in_file_extension])
    output = models.FileField(upload_to=testcase_directory_upload, validators=[validate_testcase_out_file_extension])
                                                                                                    
    class Meta:
        unique_together = ('problem', 'input', 'output')

    def __str__(self):
        return self.problem.title + ' test case ' + self.name

AOJ/competitive/forms.py
from django import forms
from .models import Submit, Language
from problem.models import Problem
# from django_ace import AceWidget


class SubmitAnswer(forms.ModelForm):
    class Meta:
        model = Submit
        fields = ['problem', 'language', 'submit_file']

class SubmitWithEditor(forms.Form):
    source = forms.CharField(widget=forms.Textarea) 
    problem = forms.ChoiceField(widget=forms.Select)
    language =  forms.ChoiceField(widget=forms.Select)

AOJ/problem/forms.py
from django import forms
from .models import Problem, TestCase
from authentication.validators import validate_problem_file_extension
from django.forms.widgets import TextInput
class AddProblem(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['title', 'short_name', 'pdf', 'time_limit', 'memory_limit', 'point', 'ballon', 'error', 'is_public']
        help_texts = {
            'title': "* Enter title of problem",
            'short_name': "* Enter short name of problem it must be less than 11 characters",
            'pdf': "* Choose problem pdf",
            'time_limit': "*Enter time limit of the problem in second",
            'memory_limit': "Enter memory limit of the problem in megabytes",
            'point': "*Enter point for the problem",
            'ballon': "choose ballon color for the problem",
        }
        widgets = {
            'pdf': forms.FileInput,
            'ballon': TextInput(attrs={'type': 'color'}),
        }
    def clean(self):
        cleaned_data = super().clean()
        pdf = cleaned_data.get('pdf')
        title = cleaned_data.get('title')
        short_name = cleaned_data.get('short_name')
        time_limit = cleaned_data.get('time_limit')
        point = cleaned_data.get('point')

        if (not pdf) or (not title) or (not time_limit)  or (not point) or (not short_name):
            raise forms.ValidationError("Please correct the errors below.")

        return cleaned_data



class EditProblem(forms.ModelForm):

    class Meta:
        model = Problem
        fields = ['title', 'short_name', 'time_limit', 'memory_limit', 'pdf', 'point', 'ballon', 'error', 'is_public']
        help_texts = {
            'title': "* Enter title of problem",
            'short_name': "* Enter short name of problem it must be less than 11 characters",
            'pdf': "* Choose problem pdf",
            'time_limit': "*Enter time limit of the problem in second",
            'memory_limit': "Enter memory limit of the problem in megabytes",
            'point': "*Enter point for the problem",
            'ballon': "choose ballon color for the problem",
        }
        widgets = {
            'pdf': forms.FileInput,
            'ballon': TextInput(attrs={'type': 'color'}),
        }
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        short_name = cleaned_data.get('short_name')
        time_limit = cleaned_data.get('time_limit')
        point = cleaned_data.get('point')

        if (not title) or (not time_limit)  or (not point) or (not short_name):
            raise forms.ValidationError("Please correct the errors below.")

        return cleaned_data


class AddProblemZIP(forms.Form):

    file = forms.FileField(
        label='ZIP file',
        help_text='* choose ZIP file.'
    )
    
class AddTestcase(forms.ModelForm):
    class Meta:
        model = TestCase
        fields = ['input', 'output']
        help_texts = {
            'input': "* Choose sample input, the file extension must be .in",
            'output': "* Choose sample output , the file extension must be .out",
        }
 

AOJ/competitive/templates/jury_scoreboard.html
{% extends base_page %}

{% block title%}Scoreboard{% endblock %}
{% block content %}  
{% load static %} 
{% load js %} 

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"  type="text/css" />

    <div class="content" id="active_contest_scoreboard">
    {% if not request.session.active_contest_admin %}
        <div class="container nocontest">
            <h5 class="ur-card-title" style="font-size: 2em;">There is no active contest</h5>
        </div>
    {% elif not request.session.start_contest_admin %}
    <div>
        <h5 class="ur-card-title" style="font-size: 1.5em;">contest {{contest_title}} start on {{start_time}}</h5>
    </div>
    {% elif scoreboard %}
        <div class="contest-name">
            Scoreboard {{ contest.title }}
        </div>
        <br> 
        <div class="scoreboard">
            <table style="border-collapse: separate;">
                <tr >
                    <thead>
                        <th class="th bottom right">RN </th>
                        <th class="th bottom right">TEAM</th>
                        <th class="th bottom right score">∑</th>
                        <th class="th bottom right score">PEN</th>
                        {% for i in total_problems%}
                            <th class="th bottom score">
                                <a href="{{i.pdf.url}}"> {{i.short_name}} <span style="height: 15px; width: 15px; background-color: {{i.ballon}}; 
                                    border-radius: 50%; display: inline-block;"></span> </a> </th>
                        {%endfor%}
                    
                    </thead>
                </tr>
                {% if scoreboard.scoreboard_jury %}
                    {% for point, punish_time, last_submit_time, teamname, user_id, univname, flag, cell_data, rank in scoreboard.scoreboard_jury %}
                    <tr>
                        <tbody>                               
                            <td class="td right"> {{rank}} </td>
                            <td class="td right team">
                                <img src="{% static flag %}">
                                <div id="teamname"> {{teamname}} </div>
                                <div id="univname"> {{univname}}</div>
                            </td>
                            <td class="td right score">{{point}}</td>
                            <td class="td right score">{{punish_time}}</td>
                            {% for try, time, color, prob_id in cell_data %}
                                {% if not color == '#ffffff' %}
                                    <td class="td score" style="background-color: {{ color }}" 
                                        onclick="cellClick('{{user_id}}', '{{prob_id}}', '{{contest.id}}')">
                                        
                                    {% if not time == -1 %}
                                        <div id="time" > {{ time }} </div>
                                    {% endif %}
                                    {% if try == 1 %}
                                        <div id="try"> {{ try }} try </div> </td>
                                    {% elif not try == 0 %}
                                        <div id="try"> {{ try }} tries </div> </td>
                                    {% endif %}
                                {% else %}
                                <td class="td score"> <div id="time" > </div><div id="try">  </div> </td>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </tr>
                    {% endfor %}
                {% endif %}

                <tr>
                    {% for row in scoreboard.summary %}
                        <td style="height:40px; padding: 10px;" class="top" > <strong>{{row}}</strong> </td>
                    {% endfor %}
                </tr>
            </table> 

            
            <div class="container col-9" style="margin-top: 50px; float: left;" >
                <p><strong>Cell colours</strong></p>
                <table >
                    <tr>
                        <td style="background-color:#26ac0c; height:20px; width:100px;font-size:16px;"> 
                            <strong>solved first</strong>
                        </td>

                        <td style="background-color:#2ef507; height:20px; width:100px; font-size:16px; "> 
                            <strong>solved</strong>
                        </td>
                        <td style="background-color:#F67B51 ; height:20px; width:120px; font-size:14px;"> 
                            <strong>tried, incorrect</strong>
                        </td>
                    </tr>

                </table>
            </div>
    
                
            </div>
        </div>  
        
        {% endif %}
            
    </div>
    <footer>
        <br><br><br>
    </footer>
    {% if request.session.current_contest_start_time and request.session.current_contest_end_time %}
    <script>
        var countDownDate_start = "{{request.session.current_contest_start_time}}";
        var countDownDate_end = "{{request.session.current_contest_end_time}}";
    </script>
    {% else %}
    <script>
        var countDownDate_start = 0;
        var countDownDate_end = 0;
    </script>
    {% endif %}
     
    <script>
        function cellClick(user_id, problem_id, contest_id){
            $.ajax({ 
                url:"{% url 'specific_problem_submission' %}",
                data:{
                    'problem_id': problem_id,
                    'user_id': user_id,
                    'contest_id': contest_id,
                },
                success: function(data){
                    document.open();
                    document.write(data);
                    document.close();
                }
            }); 
        }

        // setInterval(function(){
        //     $.ajax({ 
        //         url:"{% url 'jury_scoreboard_refresh' %}",
        //         success: function(data){
        //             if(data){
        //                 $("#active_contest_scoreboard").html(data);
        //             }
        //         }
        //     }); 

        // }, 5000);
    </script>
 
{% endblock %}

AOJ/competitive/templates/public_scoreboard.html
{% extends base_page %}

{% block timeandselector%}
<div class="time">
    <p id="countdown"></p>
    {% if request.session.all_active_contest_list_public %}
    <li id="contest_selector" class="ur-nav-item">
        <select id="id_contest" name="contest">
            {% for id, title in request.session.all_active_contest_list_public %}
                {% if id|slugify ==  request.session.active_contest_public %}
                    <option   value="{{id}}" selected="selected" > {{title|upper}}</option>
                {% else %}
                    <option   value="{{id}}">{{title}}</option>
                {%endif%}
            {%endfor%}
        </select> 
    </li>
    {%endif%}
</div>
{% endblock %}
{% block content %}  
{% load static %} 
{% load js %} 

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"  type="text/css" />

    <div class="content" id="active_contest_scoreboard">
   
    {% if scoreboard %}
        <div class="contest-name">
            Scoreboard {{ contest.title }}
        </div>
        {% if frozen %}
        <h5 style="font-size: 1.5em; color:red; margin-left:5%">The scoreboard is now frozen until {{frozen.1}}</h5>
        {% endif %}
        <br> 
        <div class="scoreboard">
            <table style="border-collapse: separate;">
                <tr >
                    <thead>
                        <th class="th bottom right">RN </th>
                        <th class="th bottom right">TEAM</th>
                        <th class="th bottom right score">∑</th>
                        <th class="th bottom right score">PEN</th>
                        {% for i in total_problems%}
                            <th class="th bottom score">
                                <a href=""> {{i.short_name}} <span style="height: 15px; width: 15px; background-color: {{i.ballon}}; 
                                    border-radius:50%; display: inline-block;"></span> </a> </th>
                        {%endfor%}
                    
                    </thead>
                </tr>
                {% if scoreboard.scoreboard_public %}
                    {% for point, punish_time, last_submit_time, teamname, user_id, univname, flag, cell_data, rank in scoreboard.scoreboard_public %}
                    <tr>
                        <tbody>     
                                                      
                            <td class="td right"> {{rank}} </td>
                            <td class="td right team">
                                <img src="{% static flag %}">
                                <div id="teamname"> {{teamname}} </div>
                                <div id="univname"> {{univname}}</div>
                            </td>
                            <td class="td right score">{{point}}</td>
                            <td class="td right score">{{punish_time}}</td>
                            {% for try, time, color in cell_data %}
                                {% if not color == '#ffffff' %}
                                    <td class="td score" style="background-color: {{ color }}">
                                    {% if not time == -1 %}
                                        <div id="time" > {{ time }} </div>
                                    {% endif %}
                                    {% if try == 1 %}
                                        <div id="try"> {{ try }} try </div> </td>
                                    {% elif not try == 0 %}
                                        <div id="try"> {{ try }} tries </div> </td>
                                    {% endif %}
                                {% else %}
                                <td class="td score"> <div id="time" > </div><div id="try">  </div> </td>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </tr>
                    {% endfor %}
                {% endif %}

                <tr>
                    {% for row in scoreboard.summary %}
                        <td style="height:40px; padding: 10px;" class="top" > <strong>{{row}}</strong> </td>
                    {% endfor %}
                </tr>
            </table> 

            
            <div class="container col-9" style="margin-top: 50px; float: left;" >
                <p><strong>Cell colours</strong></p>
                <table >
                    
                    <tr>
                        <td style="background-color:#26ac0c; height:20px; width:100px;font-size:16px;"> 
                            <strong>solved first</strong>
                        </td>

                        <td style="background-color:#2ef507; height:20px; width:100px; font-size:16px; "> 
                            <strong>solved</strong>
                        </td>
                        <td style="background-color:#F67B51 ; height:20px; width:120px; font-size:14px;"> 
                            <strong>tried, incorrect</strong>
                        </td>

                        <td style="background-color:#007F7F;height:20px; width:100px;font-size:16px;"> 
                            <strong>frozen</strong>
                        </td>
                    </tr>

                </table>
            </div>
    
        </div> 
    {% elif request.session.active_contest_public or  request.session.active_contest_contestant %}
        <div>
            <h5 class="ur-card-title" style="font-size: 1.5em;">contest {{contest_title}} start on {{start_time}}</h5>
        </div>
        
    {% else %}
        <div class="container nocontest">
            <h5 class="ur-card-title" style="font-size: 2em;">There is no active contest here</h5>
            
            {% if role == 'public' %}
            <div>
                <p>Competitive programming comprises the art of programming and critical thinking as well as problem solving. In short
                    competitive programming is about solving real world problems and also well-known
                    mathematical problems using computer programming and algorithms.
                    There are many competitions held in those countries, one of the biggest</p>
                <p>
                    competitions is the ICPC (International Collegiate Programming Contest) and it is for university
                    students who fulfill the requirements laid by the organization which hosts the competition. Many
                    universities come together from all around the world and compete for the grand prize and also it
                    is helpful for mega tech companies for recruitment.</p>
                <p>The ICPC is the world’s premiere university programming competition that is held globally. Last
                    year alone, 40,266 students from 2,736 universities and 102 countries across the globe competed
                    for the privilege of advancing to the ICPC World Finals. In the last 15 years, the competition was
                    sponsored by IBM. Now many international corporations are waiting in the queue to sponsor this
                    competition including Google and Facebook.
                    ICPC is the oldest, largest and most prestigious programming contest which has been exercised
                    for the last four decades in the world. In Africa, this contest was conducted for the 21st time this
                    year. ASTU, is the first University from Ethiopia which continuously participated in this contest
                    beginning from 2017. In the 2019 South Africa Regional ICPC Contest, 12 African Universities
                    participated and the </p>
            </div>
            {%endif%}
        </div>
               
    {% endif %}
    </div>  

    {% if request.session.current_contest_start_time and request.session.current_contest_end_time %}
    <script>
        var countDownDate_start = "{{request.session.current_contest_start_time}}";
        var countDownDate_end = "{{request.session.current_contest_end_time}}";
    </script>
    {% else %}
    <script>
        var countDownDate_start = 0;
        var countDownDate_end = 0;
    </script>
    {% endif %}
     
    <script> 

//    setInterval(function(){
//          $.ajax({ 
//              url:"{% url 'public_scoreboard_refresh' %}",
//              success: function(data){
//                  $("#active_contest_scoreboard").html(data);
//              }
//          }); 

//     }, 5000); 
    </script>
 
    {% endblock %}